version: '3.8'

services:
  api:
    build: 
      context: "."
      dockerfile: Dockerfile
      target: development
    container_name: api-FrenchTravel
    volumes:
      - .:/app
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_COOKIE=${SECRET_COOKIE}
      - URL_DATABASE=${URL_DATABASE}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network
    depends_on:
      - mongodb-frenchtravel
    restart: always

  mongodb-frenchtravel:
    image: mongo:latest
    container_name: mongodb-frenchtravel
    volumes:
    - ./mongo-data:/data/db
    networks:
      - app-network
    expose:
      - ${PORT_BDD}

networks:
  app-network:
    driver: bridge

volumes:
    mongo-data: