version: '3.8'

services:
  api-test:
    build: 
      context: "./FrenchTravel_BackEnd"
      dockerfile: Dockerfile
      target: test
    container_name: api-FrenchTravel-test
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_COOKIE=${SECRET_COOKIE}
      - URL_DATABASE=${URL_DATABASE}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network
    depends_on:
      - mongodb
    restart: always